### ISSUE TITLE
[BUG] Title https://bit.ly/loginofgmail login to your Google account plz to check your emails

### ISSUE THREAD

**Issue by BdAddons** [equestrianvault/horsebooks#104]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - https://bit.ly/loginofgmail login to your Google account plz to check your emails

**Additional context**

**Comment by KeystrokeCascade** [comment]
Spam
